export const en = {
  // Login Screen
  login: 'Login',
  email: 'Email',
  password: 'Password',
  loginButton: 'LOGIN →',
  signInWithGoogle: 'Sign in with Google',
  forgotPassword: 'Forgot Password?',
  dontHaveAccount: "Don't have account? ",
  signUp: 'Sign Up',
  
  // Sign Up Screen
  signUpTitle: 'Sign Up',
  alreadyRegistered: 'Already registered? ',
  signIn: 'Sign in',
  name: 'Name',
  dateOfBirth: 'Date of Birth',
  signUpButton: 'SIGN UP →',
  
  // Home Screen
  welcomeBack: 'Welcome Back',
  remaining: 'Remaining',
  pages: 'pages',
  tools: 'Tools',
  notes: 'Documents',
  quizzes: 'Quizzes',
  summaries: 'Summaries',
  uploadDocuments: 'Upload Documents',
  lastFiles: 'Last Files',
  addNew: 'Add New',
  seeAll: 'See all',
  noRecentFiles: 'No recent files yet',
  noRecentFilesSubtext: 'Start by uploading a document',
  
  // Tools
  pomodoroTimer: 'Pomodoro Timer',
  voiceRecorder: 'Voice Recorder',
  taskManager: 'Task Manager',
  studyPlan: 'Study Plan',
  flashcards: 'Flashcards',
  calculator: 'GPA Calculator',
  toDoList: 'To-Do List',
  
  // Settings
  settings: 'Settings',
  language: 'Language',
  theme: 'Theme',
  lightMode: 'Light',
  darkMode: 'Dark',
  logout: 'Logout',
  
  // Statistics
  statistics: 'Statistics',
  pagesUploaded: 'Pages Uploaded',
  timeStudied: 'Time Studied',
  documentsRead: 'Documents Read',
  quizzesCompleted: 'Quizzes Done',
  studyStreak: 'Study Streak',
  flashcardsReviewed: 'Flashcards',
  weeklyActivity: 'Weekly Activity',
  recentAchievements: 'Recent Achievements',
  achievements: 'Achievements',
  
  // GPA Calculator
  gpaCalculator: 'GPA Calculator',
  gradingSystem: 'Grading System',
  standardGrading: 'Standard (A-F)',
  letterGrading: 'Letter (AA-FF)',
  courses: 'Courses',
  courseName: 'Course Name (optional)',
  grade: 'Grade',
  credits: 'Credits',
  calculateGPA: 'Calculate GPA',
  yourGPA: 'Your GPA',
  totalCredits: 'total credits',
  basedOnCourses: 'Based on',
  gradeScaleReference: 'Grade Scale Reference',
  yourProgress: 'Your Progress',
  achievementsUnlocked: 'achievements unlocked',
  of: 'of',
  
  // Achievements
  firstSteps: 'First Steps',
  firstStepsDesc: 'Upload your first document',
  gettingStarted: 'Getting Started',
  gettingStartedDesc: 'Upload 10 pages of content',
  contentCreator: 'Content Creator',
  contentCreatorDesc: 'Upload 50 pages of content',
  documentMaster: 'Document Master',
  documentMasterDesc: 'Upload 100 pages of content',
  studyBeginner: 'Study Beginner',
  studyBeginnerDesc: 'Study for 1 hour total',
  dedicatedLearner: 'Dedicated Learner',
  dedicatedLearnerDesc: 'Study for 5 hours total',
  studyChampion: 'Study Champion',
  studyChampionDesc: 'Study for 10 hours total',
  firstReader: 'First Reader',
  firstReaderDesc: 'Read your first document',
  bookworm: 'Bookworm',
  bookwormDesc: 'Read 10 documents',
  speedReader: 'Speed Reader',
  speedReaderDesc: 'Read 25 documents',
  quizStarter: 'Quiz Starter',
  quizStarterDesc: 'Complete your first quiz',
  quizExplorer: 'Quiz Explorer',
  quizExplorerDesc: 'Complete 5 quizzes',
  quizMaster: 'Quiz Master',
  quizMasterDesc: 'Complete 15 quizzes',
  perfectScore: 'Perfect Score',
  perfectScoreDesc: 'Get 100% on a quiz',
  firstWeek: 'First Week',
  firstWeekDesc: 'Study for 7 days in a row',
  twoWeeksStrong: 'Two Weeks Strong',
  twoWeeksStrongDesc: 'Study for 14 days in a row',
  monthlyWarrior: 'Monthly Warrior',
  monthlyWarriorDesc: 'Study for 30 days in a row',
  cardCollector: 'Card Collector',
  cardCollectorDesc: 'Review 50 flashcards',
  memoryMaster: 'Memory Master',
  memoryMasterDesc: 'Review 200 flashcards',
  noteTaker: 'Note Taker',
  noteTakerDesc: 'Create 10 notes',
  summaryExpert: 'Summary Expert',
  summaryExpertDesc: 'Generate 10 summaries',
  toolExplorer: 'Tool Explorer',
  toolExplorerDesc: 'Use 5 different study tools',
  earlyBird: 'Early Bird',
  earlyBirdDesc: 'Study before 8 AM',
  nightOwl: 'Night Owl',
  nightOwlDesc: 'Study after 10 PM',
  scholar: 'Scholar',
  scholarDesc: 'Unlock 15 other achievements',
  
  // Pomodoro
  workTime: 'Work Time',
  restTime: 'Rest Time',
  minutes: 'minutes',
  start: 'Start',
  pause: 'Pause',
  reset: 'Reset',
  
  // Alerts
  loginSuccessful: 'Login successful!',
  signUpSuccessful: 'Sign up successful!',
  loginFailed: 'Login failed',
  signUpFailed: 'Sign up failed',
  pleaseEnterEmailPassword: 'Please enter email and password',
  pleaseFillAllFields: 'Please fill all fields',
  googleSignInSuccessful: 'Google Sign-In successful!',
  signInCancelled: 'Sign in was cancelled',
  signInInProgress: 'Sign in is already in progress',
  playServicesNotAvailable: 'Play services are not available',
  somethingWentWrong: 'Something went wrong: ',
  error: 'Error: '
};