export const es = {
  // Login Screen
  login: 'Iniciar sesión',
  email: 'Correo electrónico',
  password: 'Contraseña',
  loginButton: 'INICIAR SESIÓN →',
  signInWithGoogle: 'Iniciar sesión con Google',
  forgotPassword: '¿Olvidaste tu contraseña?',
  dontHaveAccount: '¿No tienes cuenta? ',
  signUp: 'Registrarse',
  
  // Sign Up Screen
  signUpTitle: 'Registrarse',
  alreadyRegistered: '¿Ya estás registrado? ',
  signIn: 'Iniciar sesión',
  name: 'Nombre',
  dateOfBirth: 'Fecha de nacimiento',
  signUpButton: 'REGISTRARSE →',
  
  // Home Screen
  welcomeBack: 'Bienvenido de nuevo',
  remaining: 'Restante',
  pages: 'páginas',
  tools: 'Herramientas',
  notes: 'Notas',
  quizzes: 'Cuestionarios',
  summaries: 'Resúmenes',
  uploadDocuments: 'Subir documentos',
  lastFiles: 'Últimos archivos',
  addNew: 'Agregar nuevo',
  seeAll: 'Ver todo',
  noRecentFiles: 'Aún no hay archivos recientes',
  noRecentFilesSubtext: 'Comience subiendo un documento',
  
  // Tools
  pomodoroTimer: 'Temporizador Pomodoro',
  voiceRecorder: 'Grabadora de Voz',
  taskManager: 'Gestor de Tareas',
  studyPlan: 'Plan de Estudio',
  flashcards: 'Tarjetas de Memoria',
  calculator: 'Calculadora GPA',
  toDoList: 'Lista de Tareas',
  
  // Statistics
  statistics: 'Estadísticas',
  pagesUploaded: 'Páginas Subidas',
  timeStudied: 'Tiempo Estudiado',
  documentsRead: 'Documentos Leídos',
  quizzesCompleted: 'Cuestionarios Completados',
  studyStreak: 'Racha de Estudio',
  flashcardsReviewed: 'Tarjetas Revisadas',
  weeklyActivity: 'Actividad Semanal',
  recentAchievements: 'Logros Recientes',
  achievements: 'Logros',
  
  // GPA Calculator
  gpaCalculator: 'Calculadora GPA',
  gradingSystem: 'Sistema de Calificación',
  standardGrading: 'Estándar (A-F)',
  letterGrading: 'Letras (AA-FF)',
  courses: 'Cursos',
  courseName: 'Nombre del Curso (opcional)',
  grade: 'Calificación',
  credits: 'Créditos',
  calculateGPA: 'Calcular GPA',
  yourGPA: 'Tu GPA',
  totalCredits: 'créditos totales',
  basedOnCourses: 'Basado en',
  gradeScaleReference: 'Referencia de Escala de Calificación',
  yourProgress: 'Tu Progreso',
  achievementsUnlocked: 'logros desbloqueados',
  of: 'de',
  
  // Achievements
  firstSteps: 'Primeros Pasos',
  firstStepsDesc: 'Sube tu primer documento',
  gettingStarted: 'Comenzando',
  gettingStartedDesc: 'Sube 10 páginas de contenido',
  contentCreator: 'Creador de Contenido',
  contentCreatorDesc: 'Sube 50 páginas de contenido',
  documentMaster: 'Maestro de Documentos',
  documentMasterDesc: 'Sube 100 páginas de contenido',
  studyBeginner: 'Principiante de Estudio',
  studyBeginnerDesc: 'Estudia durante 1 hora en total',
  dedicatedLearner: 'Estudiante Dedicado',
  dedicatedLearnerDesc: 'Estudia durante 5 horas en total',
  studyChampion: 'Campeón de Estudio',
  studyChampionDesc: 'Estudia durante 10 horas en total',
  firstReader: 'Primer Lector',
  firstReaderDesc: 'Lee tu primer documento',
  bookworm: 'Ratón de Biblioteca',
  bookwormDesc: 'Lee 10 documentos',
  speedReader: 'Lector Rápido',
  speedReaderDesc: 'Lee 25 documentos',
  quizStarter: 'Iniciador de Quiz',
  quizStarterDesc: 'Completa tu primer cuestionario',
  quizExplorer: 'Explorador de Quiz',
  quizExplorerDesc: 'Completa 5 cuestionarios',
  quizMaster: 'Maestro de Quiz',
  quizMasterDesc: 'Completa 15 cuestionarios',
  perfectScore: 'Puntuación Perfecta',
  perfectScoreDesc: 'Obtén 100% en un cuestionario',
  firstWeek: 'Primera Semana',
  firstWeekDesc: 'Estudia durante 7 días seguidos',
  twoWeeksStrong: 'Dos Semanas Fuerte',
  twoWeeksStrongDesc: 'Estudia durante 14 días seguidos',
  monthlyWarrior: 'Guerrero Mensual',
  monthlyWarriorDesc: 'Estudia durante 30 días seguidos',
  cardCollector: 'Coleccionista de Tarjetas',
  cardCollectorDesc: 'Revisa 50 tarjetas de memoria',
  memoryMaster: 'Maestro de la Memoria',
  memoryMasterDesc: 'Revisa 200 tarjetas de memoria',
  noteTaker: 'Tomador de Notas',
  noteTakerDesc: 'Crea 10 notas',
  summaryExpert: 'Experto en Resúmenes',
  summaryExpertDesc: 'Genera 10 resúmenes',
  toolExplorer: 'Explorador de Herramientas',
  toolExplorerDesc: 'Usa 5 herramientas de estudio diferentes',
  earlyBird: 'Madrugador',
  earlyBirdDesc: 'Estudia antes de las 8 AM',
  nightOwl: 'Búho Nocturno',
  nightOwlDesc: 'Estudia después de las 10 PM',
  scholar: 'Erudito',
  scholarDesc: 'Desbloquea 15 logros adicionales',
  
  // Settings
  settings: 'Configuración',
  language: 'Idioma',
  theme: 'Tema',
  lightMode: 'Claro',
  darkMode: 'Oscuro',
  logout: 'Cerrar sesión',
  
  // Pomodoro
  workTime: 'Tiempo de trabajo',
  restTime: 'Tiempo de descanso',
  minutes: 'minutos',
  start: 'Iniciar',
  pause: 'Pausar',
  reset: 'Reiniciar',
  
  // Alerts
  loginSuccessful: '¡Inicio de sesión exitoso!',
  signUpSuccessful: '¡Registro exitoso!',
  loginFailed: 'Error al iniciar sesión',
  signUpFailed: 'Error al registrarse',
  pleaseEnterEmailPassword: 'Por favor ingresa email y contraseña',
  pleaseFillAllFields: 'Por favor completa todos los campos',
  googleSignInSuccessful: '¡Inicio de sesión con Google exitoso!',
  signInCancelled: 'Inicio de sesión cancelado',
  signInInProgress: 'Inicio de sesión en progreso',
  playServicesNotAvailable: 'Servicios de Play no disponibles',
  somethingWentWrong: 'Algo salió mal: ',
  error: 'Error: '
};