export const it = {
  // Login Screen
  login: 'Accedi',
  email: 'Email',
  password: 'Password',
  loginButton: 'ACCEDI →',
  signInWithGoogle: 'Accedi con Google',
  forgotPassword: 'Password dimenticata?',
  dontHaveAccount: 'Non hai un account? ',
  signUp: 'Registrati',
  
  // Sign Up Screen
  signUpTitle: 'Registrati',
  alreadyRegistered: 'Già registrato? ',
  signIn: 'Accedi',
  name: 'Nome',
  dateOfBirth: 'Data di nascita',
  signUpButton: 'REGISTRATI →',
  
  // Home Screen
  welcomeBack: 'Bentornato',
  remaining: 'Rimanenti',
  pages: 'pagine',
  tools: 'Strumenti',
  notes: 'Note',
  quizzes: 'Quiz',
  summaries: 'Riassunti',
  uploadDocuments: 'Carica documenti',
  lastFiles: 'Ultimi file',
  addNew: 'Aggiungi nuovo',
  seeAll: 'Vedi tutto',
  noRecentFiles: 'Nessun file recente ancora',
  noRecentFilesSubtext: 'Inizia caricando un documento',
  
  // Tools
  pomodoroTimer: 'Timer Pomodoro',
  voiceRecorder: 'Registratore Vocale',
  taskManager: 'Gestore Attività',
  studyPlan: 'Piano di Studio',
  flashcards: 'Schede di Memoria',
  calculator: 'Calcolatrice GPA',
  toDoList: 'Lista delle Cose da Fare',
  
  // Settings
  settings: 'Impostazioni',
  language: 'Lingua',
  theme: 'Tema',
  lightMode: 'Chiaro',
  darkMode: 'Scuro',
  logout: 'Disconnetti',
  
  // Statistics
  statistics: 'Statistiche',
  pagesUploaded: 'Pagine Caricate',
  timeStudied: 'Tempo Studiato',
  documentsRead: 'Documenti Letti',
  quizzesCompleted: 'Quiz Completati',
  studyStreak: 'Serie di Studio',
  flashcardsReviewed: 'Schede Riviste',
  weeklyActivity: 'Attività Settimanale',
  recentAchievements: 'Risultati Recenti',
  achievements: 'Risultati',
  
  // GPA Calculator
  gpaCalculator: 'Calcolatrice GPA',
  gradingSystem: 'Sistema di Voti',
  standardGrading: 'Standard (A-F)',
  letterGrading: 'Lettere (AA-FF)',
  courses: 'Corsi',
  courseName: 'Nome Corso (opzionale)',
  grade: 'Voto',
  credits: 'Crediti',
  calculateGPA: 'Calcola GPA',
  yourGPA: 'Il tuo GPA',
  totalCredits: 'crediti totali',
  basedOnCourses: 'Basato su',
  gradeScaleReference: 'Riferimento Scala Voti',
  yourProgress: 'I tuoi Progressi',
  achievementsUnlocked: 'risultati sbloccati',
  of: 'di',
  
  // Achievements
  firstSteps: 'Primi Passi',
  firstStepsDesc: 'Carica il tuo primo documento',
  gettingStarted: 'Iniziando',
  gettingStartedDesc: 'Carica 10 pagine di contenuto',
  contentCreator: 'Creatore di Contenuti',
  contentCreatorDesc: 'Carica 50 pagine di contenuto',
  documentMaster: 'Maestro dei Documenti',
  documentMasterDesc: 'Carica 100 pagine di contenuto',
  studyBeginner: 'Principiante di Studio',
  studyBeginnerDesc: 'Studia per 1 ora in totale',
  dedicatedLearner: 'Studente Dedicato',
  dedicatedLearnerDesc: 'Studia per 5 ore in totale',
  studyChampion: 'Campione di Studio',
  studyChampionDesc: 'Studia per 10 ore in totale',
  firstReader: 'Primo Lettore',
  firstReaderDesc: 'Leggi il tuo primo documento',
  bookworm: 'Topo di Biblioteca',
  bookwormDesc: 'Leggi 10 documenti',
  speedReader: 'Lettore Veloce',
  speedReaderDesc: 'Leggi 25 documenti',
  quizStarter: 'Iniziatore di Quiz',
  quizStarterDesc: 'Completa il tuo primo quiz',
  quizExplorer: 'Esploratore di Quiz',
  quizExplorerDesc: 'Completa 5 quiz',
  quizMaster: 'Maestro di Quiz',
  quizMasterDesc: 'Completa 15 quiz',
  perfectScore: 'Punteggio Perfetto',
  perfectScoreDesc: 'Ottieni il 100% in un quiz',
  firstWeek: 'Prima Settimana',
  firstWeekDesc: 'Studia per 7 giorni di fila',
  twoWeeksStrong: 'Due Settimane Forte',
  twoWeeksStrongDesc: 'Studia per 14 giorni di fila',
  monthlyWarrior: 'Guerriero Mensile',
  monthlyWarriorDesc: 'Studia per 30 giorni di fila',
  cardCollector: 'Collezionista di Schede',
  cardCollectorDesc: 'Rivedi 50 schede di memoria',
  memoryMaster: 'Maestro della Memoria',
  memoryMasterDesc: 'Rivedi 200 schede di memoria',
  noteTaker: 'Prendere Appunti',
  noteTakerDesc: 'Crea 10 note',
  summaryExpert: 'Esperto di Riassunti',
  summaryExpertDesc: 'Genera 10 riassunti',
  toolExplorer: 'Esploratore di Strumenti',
  toolExplorerDesc: 'Usa 5 strumenti di studio diversi',
  earlyBird: 'Mattiniero',
  earlyBirdDesc: 'Studia prima delle 8 del mattino',
  nightOwl: 'Gufo Notturno',
  nightOwlDesc: 'Studia dopo le 22',
  scholar: 'Studioso',
  scholarDesc: 'Sblocca 15 risultati aggiuntivi',
  
  // Pomodoro
  workTime: 'Tempo di lavoro',
  restTime: 'Tempo di riposo',
  minutes: 'minuti',
  start: 'Avvia',
  pause: 'Pausa',
  reset: 'Resetta',
  
  // Alerts
  loginSuccessful: 'Accesso riuscito!',
  signUpSuccessful: 'Registrazione riuscita!',
  loginFailed: 'Accesso fallito',
  signUpFailed: 'Registrazione fallita',
  pleaseEnterEmailPassword: 'Inserisci email e password',
  pleaseFillAllFields: 'Compila tutti i campi',
  googleSignInSuccessful: 'Accesso Google riuscito!',
  signInCancelled: 'Accesso annullato',
  signInInProgress: 'Accesso in corso',
  playServicesNotAvailable: 'Servizi Play non disponibili',
  somethingWentWrong: 'Qualcosa è andato storto: ',
  error: 'Errore: '
};