export const ru = {
  // Login Screen
  login: 'Войти',
  email: 'Электронная почта',
  password: 'Пароль',
  loginButton: 'ВОЙТИ →',
  signInWithGoogle: 'Войти через Google',
  forgotPassword: 'Забыли пароль?',
  dontHaveAccount: 'Нет аккаунта? ',
  signUp: 'Регистрация',
  
  // Sign Up Screen
  signUpTitle: 'Регистрация',
  alreadyRegistered: 'Уже зарегистрированы? ',
  signIn: 'Войти',
  name: 'Имя',
  dateOfBirth: 'Дата рождения',
  signUpButton: 'РЕГИСТРАЦИЯ →',
  
  // Home Screen
  welcomeBack: 'Добро пожаловать',
  remaining: 'Осталось',
  pages: 'страниц',
  tools: 'Инструменты',
  notes: 'Заметки',
  quizzes: 'Викторины',
  summaries: 'Сводки',
  uploadDocuments: 'Загрузить документы',
  lastFiles: 'Последние файлы',
  addNew: 'Добавить новый',
  seeAll: 'Посмотреть все',
  noRecentFiles: 'Пока нет недавних файлов',
  noRecentFilesSubtext: 'Начните с загрузки документа',
  
  // Tools
  pomodoroTimer: 'Помодоро Таймер',
  voiceRecorder: 'Диктофон',
  taskManager: 'Менеджер Задач',
  studyPlan: 'План Обучения',
  flashcards: 'Карточки',
  calculator: 'GPA Калькулятор',
  toDoList: 'Список Дел',
  
  // Statistics
  statistics: 'Статистика',
  pagesUploaded: 'Загружено страниц',
  timeStudied: 'Время изучения',
  documentsRead: 'Прочитано документов',
  quizzesCompleted: 'Пройдено тестов',
  studyStreak: 'Серия изучения',
  flashcardsReviewed: 'Просмотрено карточек',
  weeklyActivity: 'Недельная активность',
  recentAchievements: 'Недавние достижения',
  achievements: 'Достижения',
  
  // GPA Calculator
  gpaCalculator: 'GPA Калькулятор',
  gradingSystem: 'Система оценок',
  standardGrading: 'Стандарт (A-F)',
  letterGrading: 'Буквы (AA-FF)',
  courses: 'Курсы',
  courseName: 'Название курса (необязательно)',
  grade: 'Оценка',
  credits: 'Кредиты',
  calculateGPA: 'Рассчитать GPA',
  yourGPA: 'Ваш GPA',
  totalCredits: 'всего кредитов',
  basedOnCourses: 'Основано на',
  gradeScaleReference: 'Справочник по шкале оценок',
  yourProgress: 'Ваш прогресс',
  achievementsUnlocked: 'достижений разблокировано',
  of: 'из',
  
  // Achievements
  firstSteps: 'Первые Шаги',
  firstStepsDesc: 'Загрузите свой первый документ',
  gettingStarted: 'Начало Работы',
  gettingStartedDesc: 'Загрузите 10 страниц контента',
  contentCreator: 'Создатель Контента',
  contentCreatorDesc: 'Загрузите 50 страниц контента',
  documentMaster: 'Мастер Документов',
  documentMasterDesc: 'Загрузите 100 страниц контента',
  studyBeginner: 'Начинающий Студент',
  studyBeginnerDesc: 'Изучайте в общей сложности 1 час',
  dedicatedLearner: 'Преданный Ученик',
  dedicatedLearnerDesc: 'Изучайте в общей сложности 5 часов',
  studyChampion: 'Чемпион Учебы',
  studyChampionDesc: 'Изучайте в общей сложности 10 часов',
  firstReader: 'Первый Читатель',
  firstReaderDesc: 'Прочитайте свой первый документ',
  bookworm: 'Книжный Червь',
  bookwormDesc: 'Прочитайте 10 документов',
  speedReader: 'Скоростной Читатель',
  speedReaderDesc: 'Прочитайте 25 документов',
  quizStarter: 'Стартер Викторин',
  quizStarterDesc: 'Завершите свою первую викторину',
  quizExplorer: 'Исследователь Викторин',
  quizExplorerDesc: 'Завершите 5 викторин',
  quizMaster: 'Мастер Викторин',
  quizMasterDesc: 'Завершите 15 викторин',
  perfectScore: 'Идеальный Результат',
  perfectScoreDesc: 'Получите 100% в викторине',
  firstWeek: 'Первая Неделя',
  firstWeekDesc: 'Изучайте 7 дней подряд',
  twoWeeksStrong: 'Две Недели Сильно',
  twoWeeksStrongDesc: 'Изучайте 14 дней подряд',
  monthlyWarrior: 'Месячный Воин',
  monthlyWarriorDesc: 'Изучайте 30 дней подряд',
  cardCollector: 'Коллекционер Карточек',
  cardCollectorDesc: 'Просмотрите 50 карточек',
  memoryMaster: 'Мастер Памяти',
  memoryMasterDesc: 'Просмотрите 200 карточек',
  noteTaker: 'Записывающий Заметки',
  noteTakerDesc: 'Создайте 10 заметок',
  summaryExpert: 'Эксперт Сводок',
  summaryExpertDesc: 'Создайте 10 сводок',
  toolExplorer: 'Исследователь Инструментов',
  toolExplorerDesc: 'Используйте 5 различных учебных инструментов',
  earlyBird: 'Ранняя Пташка',
  earlyBirdDesc: 'Изучайте до 8 утра',
  nightOwl: 'Ночная Сова',
  nightOwlDesc: 'Изучайте после 22:00',
  scholar: 'Ученый',
  scholarDesc: 'Разблокируйте 15 других достижений',
  
  // Settings
  settings: 'Настройки',
  language: 'Язык',
  theme: 'Тема',
  lightMode: 'Светлая',
  darkMode: 'Темная',
  logout: 'Выйти',
  
  // Pomodoro
  workTime: 'Время работы',
  restTime: 'Время отдыха',
  minutes: 'минут',
  start: 'Старт',
  pause: 'Пауза',
  reset: 'Сброс',
  
  // Alerts
  loginSuccessful: 'Вход выполнен успешно!',
  signUpSuccessful: 'Регистрация успешна!',
  loginFailed: 'Ошибка входа',
  signUpFailed: 'Ошибка регистрации',
  pleaseEnterEmailPassword: 'Введите email и пароль',
  pleaseFillAllFields: 'Заполните все поля',
  googleSignInSuccessful: 'Вход через Google успешен!',
  signInCancelled: 'Вход отменен',
  signInInProgress: 'Вход в процессе',
  playServicesNotAvailable: 'Сервисы Play недоступны',
  somethingWentWrong: 'Что-то пошло не так: ',
  error: 'Ошибка: '
};