export const tr = {
  // Login Screen
  login: 'Giriş',
  email: 'E-posta',
  password: 'Şifre',
  loginButton: 'GİRİŞ →',
  signInWithGoogle: 'Google ile Giriş Yap',
  forgotPassword: 'Şifremi Unuttum?',
  dontHaveAccount: 'Hesabınız yok mu? ',
  signUp: 'Kayıt Ol',
  
  // Sign Up Screen
  signUpTitle: 'Kayıt Ol',
  alreadyRegistered: 'Zaten kayıtlı mısınız? ',
  signIn: 'Giriş Yap',
  name: 'Ad',
  dateOfBirth: 'Doğum Tarihi',
  signUpButton: 'KAYIT OL →',
  
  // Home Screen
  welcomeBack: 'Hoş Geldiniz',
  remaining: 'Kalan',
  pages: 'sayfa',
  tools: 'Araçlar',
  notes: 'Notlar',
  quizzes: 'Quizler',
  summaries: 'Özetler',
  uploadDocuments: 'Doküman Yükle',
  lastFiles: 'Son Dosyalar',
  addNew: 'Yeni Ekle',
  seeAll: 'Tümünü gör',
  noRecentFiles: 'Henüz son dosya yok',
  noRecentFilesSubtext: 'Bir doküman yükleyerek başlayın',
  
  // Tools
  pomodoroTimer: 'Pomodoro Zamanlayıcı',
  voiceRecorder: 'Ses Kaydedici',
  taskManager: 'Görev Yöneticisi',
  studyPlan: 'Çalışma Planı',
  flashcards: 'Flash Kartlar',
  calculator: 'GPA Hesaplayıcı',
  toDoList: 'Yapılacaklar Listesi',
  
  // Settings
  settings: 'Ayarlar',
  language: 'Dil',
  theme: 'Tema',
  lightMode: 'Açık',
  darkMode: 'Koyu',
  logout: 'Çıkış Yap',
  
  // Statistics
  statistics: 'İstatistikler',
  pagesUploaded: 'Yüklenen Sayfalar',
  timeStudied: 'Çalışma Süresi',
  documentsRead: 'Okunan Dokümanlar',
  quizzesCompleted: 'Tamamlanan Quizler',
  studyStreak: 'Çalışma Serisi',
  flashcardsReviewed: 'İncelenen Kartlar',
  weeklyActivity: 'Haftalık Aktivite',
  recentAchievements: 'Son Başarılar',
  achievements: 'Başarılar',
  
  // GPA Calculator
  gpaCalculator: 'GPA Hesaplayıcı',
  gradingSystem: 'Notlama Sistemi',
  standardGrading: 'Standart (A-F)',
  letterGrading: 'Harf (AA-FF)',
  courses: 'Dersler',
  courseName: 'Ders Adı (isteğe bağlı)',
  grade: 'Not',
  credits: 'Kredi',
  calculateGPA: 'GPA Hesapla',
  yourGPA: 'GPA\'nız',
  totalCredits: 'toplam kredi',
  basedOnCourses: 'Temel alınan',
  gradeScaleReference: 'Not Skalası Referansı',
  yourProgress: 'İlerlemeniz',
  achievementsUnlocked: 'başarı kazanıldı',
  of: '',
  
  // Achievements
  firstSteps: 'İlk Adımlar',
  firstStepsDesc: 'İlk dokümanınızı yükleyin',
  gettingStarted: 'Başlangıç',
  gettingStartedDesc: '10 sayfa içerik yükleyin',
  contentCreator: 'İçerik Yaratıcısı',
  contentCreatorDesc: '50 sayfa içerik yükleyin',
  documentMaster: 'Doküman Ustası',
  documentMasterDesc: '100 sayfa içerik yükleyin',
  studyBeginner: 'Çalışma Başlangıcı',
  studyBeginnerDesc: 'Toplam 1 saat çalışın',
  dedicatedLearner: 'Kararlı Öğrenci',
  dedicatedLearnerDesc: 'Toplam 5 saat çalışın',
  studyChampion: 'Çalışma Şampiyonu',
  studyChampionDesc: 'Toplam 10 saat çalışın',
  firstReader: 'İlk Okuyucu',
  firstReaderDesc: 'İlk dokümanınızı okuyun',
  bookworm: 'Kitap Kurdu',
  bookwormDesc: '10 doküman okuyun',
  speedReader: 'Hızlı Okuyucu',
  speedReaderDesc: '25 doküman okuyun',
  quizStarter: 'Quiz Başlangıcı',
  quizStarterDesc: 'İlk quizinizi tamamlayın',
  quizExplorer: 'Quiz Kaşifi',
  quizExplorerDesc: '5 quiz tamamlayın',
  quizMaster: 'Quiz Ustası',
  quizMasterDesc: '15 quiz tamamlayın',
  perfectScore: 'Mükemmel Puan',
  perfectScoreDesc: 'Bir quizde %100 alın',
  firstWeek: 'İlk Hafta',
  firstWeekDesc: '7 gün üst üste çalışın',
  twoWeeksStrong: 'İki Hafta Güçlü',
  twoWeeksStrongDesc: '14 gün üst üste çalışın',
  monthlyWarrior: 'Aylık Savaşçı',
  monthlyWarriorDesc: '30 gün üst üste çalışın',
  cardCollector: 'Kart Koleksiyoncusu',
  cardCollectorDesc: '50 kart gözden geçirin',
  memoryMaster: 'Hafıza Ustası',
  memoryMasterDesc: '200 kart gözden geçirin',
  noteTaker: 'Not Tutucu',
  noteTakerDesc: '10 not oluşturun',
  summaryExpert: 'Özet Uzmanı',
  summaryExpertDesc: '10 özet oluşturun',
  toolExplorer: 'Araç Kaşifi',
  toolExplorerDesc: '5 farklı çalışma aracı kullanın',
  earlyBird: 'Erken Kalkan',
  earlyBirdDesc: 'Sabah 8\'den önce çalışın',
  nightOwl: 'Gece Kuşu',
  nightOwlDesc: 'Akşam 22\'den sonra çalışın',
  scholar: 'Bilgin',
  scholarDesc: '15 farklı başarı kazanın',
  
  // Pomodoro
  workTime: 'Çalışma Süresi',
  restTime: 'Dinlenme Süresi',
  minutes: 'dakika',
  start: 'Başlat',
  pause: 'Duraklat',
  reset: 'Sıfırla',
  
  // Alerts
  loginSuccessful: 'Giriş başarılı!',
  signUpSuccessful: 'Kayıt başarılı!',
  loginFailed: 'Giriş başarısız',
  signUpFailed: 'Kayıt başarısız',
  pleaseEnterEmailPassword: 'Lütfen e-posta ve şifre girin',
  pleaseFillAllFields: 'Lütfen tüm alanları doldurun',
  googleSignInSuccessful: 'Google girişi başarılı!',
  signInCancelled: 'Giriş iptal edildi',
  signInInProgress: 'Giriş zaten devam ediyor',
  playServicesNotAvailable: 'Play hizmetleri mevcut değil',
  somethingWentWrong: 'Bir şeyler yanlış gitti: ',
  error: 'Hata: '
};