export const zh = {
  // Login Screen
  login: '登录',
  email: '邮箱',
  password: '密码',
  loginButton: '登录 →',
  signInWithGoogle: '使用Google登录',
  forgotPassword: '忘记密码？',
  dontHaveAccount: '没有账户？ ',
  signUp: '注册',
  
  // Sign Up Screen
  signUpTitle: '注册',
  alreadyRegistered: '已经注册？ ',
  signIn: '登录',
  name: '姓名',
  dateOfBirth: '出生日期',
  signUpButton: '注册 →',
  
  // Home Screen
  welcomeBack: '欢迎回来',
  remaining: '剩余',
  pages: '页',
  tools: '工具',
  notes: '笔记',
  quizzes: '测验',
  summaries: '摘要',
  uploadDocuments: '上传文档',
  lastFiles: '最近文件',
  addNew: '添加新文件',
  seeAll: '查看全部',
  noRecentFiles: '暂无最近文件',
  noRecentFilesSubtext: '从上传文档开始',
  
  // Tools
  pomodoroTimer: '番茄钟',
  voiceRecorder: '录音机',
  taskManager: '任务管理器',
  studyPlan: '学习计划',
  flashcards: '抽认卡',
  calculator: 'GPA计算器',
  toDoList: '待办事项',
  
  // Settings
  settings: '设置',
  language: '语言',
  theme: '主题',
  lightMode: '浅色',
  darkMode: '深色',
  logout: '退出登录',
  
  // Statistics
  statistics: '统计',
  pagesUploaded: '已上传页面',
  timeStudied: '学习时间',
  documentsRead: '已读文档',
  quizzesCompleted: '已完成测验',
  studyStreak: '学习连续天数',
  flashcardsReviewed: '已复习卡片',
  weeklyActivity: '每周活动',
  recentAchievements: '最近成就',
  achievements: '成就',
  
  // GPA Calculator
  gpaCalculator: 'GPA计算器',
  gradingSystem: '评分系统',
  standardGrading: '标准 (A-F)',
  letterGrading: '字母 (AA-FF)',
  courses: '课程',
  courseName: '课程名称（可选）',
  grade: '成绩',
  credits: '学分',
  calculateGPA: '计算GPA',
  yourGPA: '您的GPA',
  totalCredits: '总学分',
  basedOnCourses: '基于',
  gradeScaleReference: '成绩等级参考',
  yourProgress: '您的进度',
  achievementsUnlocked: '成就已解锁',
  of: '个，共',
  
  // Achievements
  firstSteps: '初步',
  firstStepsDesc: '上传您的第一个文档',
  gettingStarted: '开始',
  gettingStartedDesc: '上传10页内容',
  contentCreator: '内容创作者',
  contentCreatorDesc: '上传50页内容',
  documentMaster: '文档大师',
  documentMasterDesc: '上传100页内容',
  studyBeginner: '学习初学者',
  studyBeginnerDesc: '总共学习1小时',
  dedicatedLearner: '专注学习者',
  dedicatedLearnerDesc: '总共学习5小时',
  studyChampion: '学习冠军',
  studyChampionDesc: '总共学习10小时',
  firstReader: '第一个读者',
  firstReaderDesc: '阅读您的第一个文档',
  bookworm: '书虫',
  bookwormDesc: '阅读10个文档',
  speedReader: '快速阅读者',
  speedReaderDesc: '阅读25个文档',
  quizStarter: '测验新手',
  quizStarterDesc: '完成您的第一个测验',
  quizExplorer: '测验探索者',
  quizExplorerDesc: '完成5个测验',
  quizMaster: '测验大师',
  quizMasterDesc: '完成15个测验',
  perfectScore: '完美成绩',
  perfectScoreDesc: '在测验中获得100%',
  firstWeek: '第一周',
  firstWeekDesc: '连续学习7天',
  twoWeeksStrong: '坚持两周',
  twoWeeksStrongDesc: '连续学习14天',
  monthlyWarrior: '月度战士',
  monthlyWarriorDesc: '连续学习30天',
  cardCollector: '卡片收集者',
  cardCollectorDesc: '复习50张抽认卡',
  memoryMaster: '记忆大师',
  memoryMasterDesc: '复习200张抽认卡',
  noteTaker: '笔记记录者',
  noteTakerDesc: '创建10条笔记',
  summaryExpert: '总结专家',
  summaryExpertDesc: '生成10个总结',
  toolExplorer: '工具探索者',
  toolExplorerDesc: '使用5种不同的学习工具',
  earlyBird: '早起鸟儿',
  earlyBirdDesc: '在上午8点前学习',
  nightOwl: '夜猫子',
  nightOwlDesc: '在晚上10点后学习',
  scholar: '学者',
  scholarDesc: '解锁15个其他成就',
  
  // Pomodoro
  workTime: '工作时间',
  restTime: '休息时间',
  minutes: '分钟',
  start: '开始',
  pause: '暂停',
  reset: '重置',
  
  // Alerts
  loginSuccessful: '登录成功！',
  signUpSuccessful: '注册成功！',
  loginFailed: '登录失败',
  signUpFailed: '注册失败',
  pleaseEnterEmailPassword: '请输入邮箱和密码',
  pleaseFillAllFields: '请填写所有字段',
  googleSignInSuccessful: 'Google登录成功！',
  signInCancelled: '登录已取消',
  signInInProgress: '正在登录',
  playServicesNotAvailable: 'Play服务不可用',
  somethingWentWrong: '出现错误：',
  error: '错误：'
};